In [2]:
import numpy as np
import cirq

**E.g., bit-flip channel**

In [9]:
p = 0.01
sigma_x = cirq.unitary(cirq.X)
sigma_y = cirq.unitary(cirq.Y)
sigma_z = cirq.unitary(cirq.Z)
sigma_i = cirq.unitary(cirq.I)
hadamard = cirq.unitary(cirq.H)

In [4]:
super_opr = cirq.kraus_to_superoperator([
    np.sqrt((1-p)) * sigma_i,
    np.sqrt(p) * sigma_x
])
super_opr

array([[0.99+0.j, 0.  +0.j, 0.  +0.j, 0.01+0.j],
       [0.  +0.j, 0.99+0.j, 0.01+0.j, 0.  +0.j],
       [0.  +0.j, 0.01+0.j, 0.99+0.j, 0.  +0.j],
       [0.01+0.j, 0.  +0.j, 0.  +0.j, 0.99+0.j]])

In [5]:
choi_mat = cirq.kraus_to_choi([
    np.sqrt((1-p)) * sigma_i,
    np.sqrt(p) * sigma_x
])
choi_mat

array([[0.99+0.j, 0.  +0.j, 0.  +0.j, 0.99+0.j],
       [0.  +0.j, 0.01+0.j, 0.01+0.j, 0.  +0.j],
       [0.  +0.j, 0.01+0.j, 0.01+0.j, 0.  +0.j],
       [0.99+0.j, 0.  +0.j, 0.  +0.j, 0.99+0.j]])

In [6]:
cirq.superoperator_to_kraus(super_opr)

[array([[-0.00000000e+00+0.j,  1.31708902e-09+0.j],
        [-1.31708902e-09+0.j,  0.00000000e+00+0.j]]),
 array([[ 0. +0.j, -0.1+0.j],
        [-0.1+0.j,  0. +0.j]]),
 array([[-0.99498744+0.j,  0.        +0.j],
        [ 0.        +0.j, -0.99498744+0.j]])]

In [7]:
cirq.choi_to_kraus(choi_mat)

[array([[-0.00000000e+00+0.j,  1.31708902e-09+0.j],
        [-1.31708902e-09+0.j,  0.00000000e+00+0.j]]),
 array([[ 0. +0.j, -0.1+0.j],
        [-0.1+0.j,  0. +0.j]]),
 array([[-0.99498744+0.j,  0.        +0.j],
        [ 0.        +0.j, -0.99498744+0.j]])]

array([[0.99+0.j, 0.  +0.j, 0.  +0.j, 0.01+0.j],
       [0.  +0.j, 0.99+0.j, 0.01+0.j, 0.  +0.j],
       [0.  +0.j, 0.01+0.j, 0.99+0.j, 0.  +0.j],
       [0.01+0.j, 0.  +0.j, 0.  +0.j, 0.99+0.j]])

In [53]:
def conj_opr(opr, conj):
    return conj @ opr @ conj.conj().T

ops = [conj_opr(hadamard, pauli) for pauli in [sigma_i, sigma_x, sigma_y, sigma_z]]
bit_flip = cirq.kraus_to_superoperator([
    np.sqrt((1-p)) * sigma_i,
    np.sqrt(p) * sigma_x
])
super_ops = [bit_flip @ cirq.kraus_to_superoperator([opr]) for opr in ops]

In [54]:
coeffs = [1.0101351149324356, -0.00337837831080956, -0.003378378310809782, -0.003378378310809116]

hadamard_synthesized = np.average(super_ops, weights=coeffs, axis=0)

In [55]:
hadamard_super_opr = cirq.kraus_to_superoperator([hadamard])

np.linalg.norm(hadamard_synthesized - hadamard_super_opr, 1)

0.02675675675676281

In [68]:
cirq.is_cptp(kraus_ops=cirq.superoperator_to_kraus(np.linalg.inv(bit_flip)))

ValueError: Choi matrix must be positive, got one with eigenvalues [-2.04081633e-02  5.03069808e-17  1.11022302e-16  2.02040816e+00]

In [71]:
cirq.superoperator_to_kraus((bit_flip))

[array([[-0.00000000e+00+0.j,  1.31708902e-09+0.j],
        [-1.31708902e-09+0.j,  0.00000000e+00+0.j]]),
 array([[ 0. +0.j, -0.1+0.j],
        [-0.1+0.j,  0. +0.j]]),
 array([[-0.99498744+0.j,  0.        +0.j],
        [ 0.        +0.j, -0.99498744+0.j]])]